apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  # type: NodePort
  selector:
    app: synergychat-api
  ports:
    - port: 80 # this is the port that the service will listen on
      protocol: TCP # TCP will allow us to use HTPP
      targetPort: 8080 # this is the port that the pods are listening on
      # nodePort: 30080 # This is the port of the PC where the cluster is running
