apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap
data:
  CRAWLER_PORT: "8080" #declared explicitly as string
  CRAWLER_KEYWORDS: love,hate,joy,sadness,anger,disgust,fear,surprise