apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: synergychat-web
  ports:
    - port: 80 # this is the port that the service will listen on
      protocol: TCP # TCP will allow us to use HTPP
      targetPort: 8080 # this is the port that the pods are listening on
